include: package:dart_flutter_team_lints/analysis_options.yaml

analyzer:
  errors:
    unused_import: error
    unused_local_variable: error
    dead_code: error
    deprecated_member_use_from_same_package: ignore
    lines_longer_than_80_chars: ignore # TODO: Enable and fix

linter:
  rules:
    - avoid_unused_constructor_parameters
    - cancel_subscriptions
    - no_adjacent_strings_in_list
    - package_api_docs
    - sort_child_properties_last
